name: build-shotcut-macos-unstable

on:
  workflow_dispatch:
  schedule:
    # nightly
    - cron: '0 12 * * *'

jobs:
  build:
    #if: ${{ github.repository_owner == 'mltframework' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump log
        shell: bash
        run: |
          pwd
          ls
          pwd
