name: build-shotcut-macos-unstable

on:
  workflow_dispatch:
  schedule:
    # nightly
    - cron: '0 12 * * *'

jobs:
  build:
    #if: ${{ github.repository_owner == 'mltframework' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
      uses: actions/checkout@v3
      - name: Dump log
      run: |
        pwd
        cd ..
        ls -la
        pwd
